fix: import schema files to support bundlers
authenio/samlify-node-xmllint pull request #3
Opened 2020-04-10 23:47 UTC by shellscape

This PR changes the `/schemas` files to export a string. This directly supports use in bundlers following the precedent set by `node-xml-encryption`.  This fixes #2.

@tngan I would be happy to pay a bounty to get this update merged and published.

2020-04-11 17:20 UTC, tngan commented on index.ts
>  import * as path from 'path';
```suggestion
```

2020-04-11 17:20 UTC, tngan commented on index.ts
>  import * as fs from 'fs';
```suggestion
```

2020-04-11 17:22 UTC, tngan requested changes
There are two imports which are no longer to be used.

2020-04-11 17:22 UTC, tngan commented
@shellscape Interesting, it would serve both serverless and with-server architecture. Good work.

With this change, I will bump a major version for it, just in case if there is potential side effect that we miss. I will do it right after this ticket is being merged.

2020-04-12 01:41 UTC, shellscape commented
@tngan Done!

2020-04-12 03:07 UTC, merged

2020-04-12 04:08 UTC, shellscape commented
Thank you!